### ISSUE TITLE
User Management Endpoints

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#114]
## Attributes of a user
1. Name
2. eMail
3. Password
4. Type
5. Organisation (Foreign Key Reference to Partners)
7. Created At

## Types of Users
1. team
2. partners
3. students

## GET /users
Gives the list of all users that exist in the system.

This should also support a query parameter of `type` which will only give the users of a particular type. If the `type` query parameter is not given then it should give users of all types.

*Access:* ngTeam, students

## POST /users
Creates a new user. If the type of a user is partners then the Organisation ID will be compulsory to give otherwise it can be skipped.

Creation of a new user will also trigger them an SMS & an eMail with their username/password. Their should be be a template for this eMail.

*Access:* ngTeam

*Note:* While creating a new user check the way currently the create method in the `userService` has been written. Similarly the password of the user needs to be hashed and stored.

## PUT /users/{userId}

This endpoint will be used to edit the user.

*Access:* anyone.

A custom check at this endpoint will be needed to ensure that the logged in user and the user ID given in the path of this endpoint remain the same.

## GET /users/{userId}

This will give the details of the user with the given user ID.

## TO-DOs

- [x] GET /users
- [ ] POST /users
- [x] PUT /users/{userId}
- [x] GET /users/{userId}
- [x] Decide the auth and scope for every endpoint which has been made and document it here first. After discussion with Rishabh add that auth & scope.

**Comment by pralhad88** [comment]
the role of JWT is that it create the token for authentication purpose only those user will take access it has valid JWT token. and the role of scope is that it's check on which user to give authentication, if it is type team then it gives authentication to ngTeam user. else it does not give authentication to other user.

**Comment by RishabhVerma** [comment]
Yes. Do you have a question or you'd just written this for understanding?
