### ISSUE TITLE
Partner Tracking on Online Tests

### ISSUE THREAD

**Issue by RishabhVerma** [navgurukul/chanakya#188]
`students` table has a column called `partner_id` which can be used to track the partner which the student is associated with. But the `partner_id` column is only filled when the student test attempts are uploaded for offline tests. There is no way to track when the student answers the test online. 

Following changes need to be made in Chanakya for this.

## GET /helpline/register_exotel_call
This endpoint should also take another optional URL parameter called `partnerId`. If specified the student record created will have the corresponding `partner_id` specified in the column. If wrong is specified then an error will be thrown.

## POST /partners
A new `slug` parameter needs to be added to store the slug of the partner. Use this (https://www.regextester.com/104045) regex to validate a slug.

## PUT /partners/{partnerId}
This endpoint can now be used to edit the slug too.

## GET /partners/{slug}
Instead of just getting a partner details using their ID a partner slug can be specified too to get the partner details. This will be used by the frontend to validate if the slug given in the URL is right.

**Comment by abhishekgupta92** [comment]
- [ ] Get token using google-auth library
- [ ] Make an API call to the server /auth/login/google
- [ ] Get token from the server
- [ ] Store token and user details in the localhost
- [ ] Add a function in the utils for user authentication
- [ ] Create redux endpoints for usage throughout the app

**Comment by pralhad88** [comment]
[ ]  creating issue for testing

**Comment by pralhad88** [comment]
- [ ] just creating check box issue 

- [ ] second check box

**Comment by abhishekgupta92** [comment]
@pralhad88 and @RishabhVerma - this is done, right?
